const inputConfigurationsMap = {
  personal: [
    {
      label: 'Full Name',
      type: 'text',
      name: 'fullName',
      id: 'fullName',
      placeholder: 'First and Last Name',
      autoComplete: 'name',
    },
    {
      label: 'Email',
      type: 'email',
      name: 'email',
      id: 'email',
      placeholder: 'Enter Email',
      autoComplete: 'email',
    },
    {
      label: 'Phone Number',
      type: 'tel',
      name: 'phoneNumber',
      id: 'phoneNumber',
      placeholder: 'Enter Phone Number',
      autoComplete: 'tel',
    },
    {
      label: 'Address',
      type: 'text',
      name: 'address',
      id: 'address',
      placeholder: 'City, Country',
      autoComplete: 'street-address',
    },
  ],
  education: [
    {
      label: 'School',
      type: 'text',
      name: 'school',
      id: 'school',
      placeholder: 'Enter School / College',
      autoComplete: 'organization',
    },
    {
      label: 'Degree',
      type: 'text',
      name: 'degree',
      id: 'degree',
      placeholder: 'Enter Degree / Field of Study',
      autoComplete: 'education-level',
    },

    {
      label: 'Start Date',
      type: 'text',
      name: 'startStudy',
      id: 'startStudy',
      placeholder: 'Enter Start Date',
      autoComplete: 'off',
    },
    {
      label: 'End Date',
      type: 'text',
      name: 'endStudy',
      id: 'endStudy',
      placeholder: 'Enter End Date',
      autoComplete: 'off',
    },
    {
      label: 'Location',
      type: 'text',
      name: 'locationStudy',
      id: 'locationStudy',
      placeholder: 'Enter Location',
      autoComplete: 'off',
    },
  ],
  experience: [
    {
      label: 'Company Name',
      type: 'text',
      name: 'company',
      id: 'company',
      placeholder: 'Enter Company Name',
      autoComplete: 'organization',
    },
    {
      label: 'Position Title',
      type: 'text',
      name: 'position',
      id: 'position',
      placeholder: 'Enter Position Title',
      autoComplete: 'job-title',
    },
    {
      label: 'Start Date',
      type: 'text',
      name: 'startWork',
      id: 'startWork',
      placeholder: 'Enter Start Date',
      autoComplete: 'off',
    },
    {
      label: 'End Date',
      type: 'text',
      name: 'endWork',
      id: 'endWork',
      placeholder: 'Enter End Date',
      autoComplete: 'off',
    },
    {
      label: 'Location',
      type: 'text',
      name: 'locationWork',
      id: 'locationWork',
      placeholder: 'Enter Location',
      autoComplete: 'off',
    },
    {
      label: 'Description',
      type: 'text',
      name: 'descriptionWork',
      id: 'descriptionWork',
      placeholder: 'Enter Description',
      autoComplete: 'off',
    },
  ],
};

export default inputConfigurationsMap;
